### ISSUE TITLE
filter_copy.cpp missing

### ISSUE THREAD

**Issue by kls0e** [aclemons/emailrelay#1]
I'm trying to build on a raspberry 3b running raspbian buster, build fails since filter_copy.cpp is missing.

**Comment by aclemons** [comment]
This is just an unofficial git mirror of the canonical repo (https://emailrelay.sourceforge.net/ / https://svn.code.sf.net/p/emailrelay/code/). I sent Graeme my scripts back when this was setup for how I migrated the svn repo to git, but I think he was quite happy to leave the repo as is on sf.

I've just re-synced this repo so this should be up to date now with what's there. If you still have problems, please open an issue with Graeme over on sourceforge. Thanks.

**Comment by stokito** [comment]
@kls0e  I created an Ubuntu PPA based on the repo. It builds also for the Raspberry PI.

https://code.launchpad.net/~stokito/+archive/ubuntu/emailrelay


Here you may download individual debs:
https://code.launchpad.net/~stokito/+archive/ubuntu/emailrelay/+packages

Click on the package icon and you'll find a link.
Here is an example:
https://code.launchpad.net/~stokito/+archive/ubuntu/emailrelay/+files/emailrelay_2.4-0~202209301856~ubuntu20.04.1_armhf.deb

**Comment by stokito** [comment]
@aclemons if you are already maintain the repo then you can also maintain the PPA. If you are interested call me in telegram stokito and I'll quickly show you how to configure the PPA.
Btw there was one build bug https://sourceforge.net/p/emailrelay/support-requests/74/

**Comment by aclemons** [comment]
I don't use ubuntu or any ubuntu-based distribution, so I'm unfortunately not interested.
