### ISSUE TITLE
email relay invalid secret file

### ISSUE THREAD

**Issue by orb71** [aclemons/emailrelay#3]
Hello,

I am unable to start it when base64 encoding is used. The syntax and the coding in the auth file are correct.
md5 or plain work as expected.

emailrelay: 20230103.105453.678: warning: problems reading secrets file [C:\ProgramData\E-MailRelay\emailrelay.auth]...
emailrelay: 20230103.105453.679: warning: emailrelay.auth(12): invalid xtext encoding in dfourth field

Windows, v2.4 

Regards,
Oli

**Comment by aclemons** [comment]
This is just a git mirror of the emailrelay SVN repo which Graeme maintains on Sourceforge. Could you open an issue for him there please? https://sourceforge.net/p/emailrelay/_list/tickets
