### ISSUE TITLE
How to see realtime logs when using start as service

### ISSUE THREAD

**Issue by sinankizar** [aclemons/emailrelay#5]
We are grateful for this litlle big app and using it in our production server since ms disabled some features. Thanks again.

Now I want to see live logs when started as service. If I setup start with login then I can see a tray icon and if I double click I can monitor realtime logs. But if i start as service there are no tray icons and couldn't find a way to watch them. Is there a way to aciheve this?

Thanks in advance

**Comment by aclemons** [comment]
Hi @sinankizar, this repo is just a mirror of emailrelay in git. Could you please open an issue for Graeme here: https://sourceforge.net/projects/emailrelay/support

Thanks
